name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - feature/ci-crosplatform-test

jobs:
  phpunit:
    name: PHPUnit (${{ matrix.php-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs:
      - phpstan
      - php-cs-fixer
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts

      - name: Run PHPUnit
        run: php "-dzend.assertions=1" vendor/bin/phpunit

  phpstan:
    name: PHPStan (${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  php-cs-fixer:
    name: PHP-CS-Fixer (${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts

      - name: Run PHP-CS-Fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --dry-run --diff
